.github/workflows/main.yml
We won't be able to test this until after this PR is merged. @antgonza @ccowart
=> MAINT: Add github actions CI

.github/workflows/main.yml, README.md, amplicon-pooling.ipynb, metagenomics_pipeline_qPCRnorm.ipynb, metagenomics_samplesheet_generator.ipynb, metapool/metapool.py, metapool/tests/test_metapool.py, metapool/tests/test_prep.py
=> STY: Flake8tify the codebase

metapool/prep.py, metapool/tests/test_prep.py
=> ENH: Add zero-padding for AGP sample names

amplicon-pooling.ipynb, metapool/sample_sheet.py, metapool/scripts/seqpro.py, metapool/scripts/tests/test_seqpro.py, metapool/tests/test_sample_sheet.py
Most of these changes came up after I met with MacKenzie to go over the notebook. In summary:
- There was a bug with merging Bioinformatics/Contact sections.
- Merging sample sheets should ignore date differences.
- I updated the wording in the amplicon notebook to refer to preparations files as mapping files.
- Added tests for the seqpro CLI. Looks like the updates to the API didn't make it there so I added a new test module and updated the API.
=> Post review fixes

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
I found this while looking at a sample sheet *in the wild*.
=> ENH: Add bcl2fastq scrubbing for project names

amplicon-pooling.ipynb, iTru index combo generator.ipynb, metagenomics_pipeline_qPCRnorm.ipynb, metagenomics_repooling.ipynb, sample-sheet-validation.ipynb, setup.py
This will help keep track of what versions were installed when the
notebooks were run.
https://github.com/rasbt/watermark
=> ENH: Add watermark to notebooks

amplicon-pooling.ipynb, metagenomics_samplesheet_generator.ipynb, metapool/igm.py, metapool/tests/test_igm.py
Most of the suggestions were made by MacKenzie. She noted that project_number and task_number mostly always stay the same. And that we don't really need the Manifest generation for 16S data, so I moved this to the metagenomics notebook.
=> Improve IGM Manifest code

amplicon-pooling.ipynb, iTru index combo generator.ipynb, metagenomics_pipeline_qPCRnorm.ipynb, metagenomics_repooling.ipynb, metagenomics_samplesheet_generator.ipynb, metapool/__init__.py, metapool/igm.py, metapool/sample_sheet.py, metapool/tests/test_igm.py, metapool/tests/test_sample_sheet.py, sample-sheet-validation.ipynb
- Renames `validate_sample_sheet` to `validate_and_scrub_sample_sheet`.
- Adds `__str__` to `IGMManifest` and outputs that when a manifest is written to a file.
- Includes a few updates to the notebooks including a bug fix of a mislabeled column.
=> Code review comments

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
This function won't print errors and warnings to stdout, instead it will return a list of objects and a sample sheet or None.
=> ENH: Add a quiet variant of the sample sheet validation

metapool/prep.py, metapool/sample_sheet.py, metapool/tests/test_prep.py, metapool/tests/test_sample_sheet.py
We scrub the original sample identifier to make it Qiita compliant and
store it in well_description.
Fixes #46
=> ENH: Add well description generation

metapool/prep.py, metapool/tests/test_prep.py
=> Update error text for parsing run ID

notebooks/amplicon_mapping_file_generator.ipynb
Minor changes to finish up the amplicon notebook. Worked and reviewed by @mmbryant23.
=> minor changes

setup.py
Updated scikit-learn dependency to install properly for mg-scripts and metapool packages.
Prep-file generation support needed.
=> Amplicon support #1

metapool/count.py, metapool/prep.py, metapool/scripts/seqpro_mf.py, metapool/scripts/tests/test_seqpro_mf.py, metapool/tests/test_prep.py, setup.py
Modifications based on testing on qiita-rc.
=> Modifications based on testing

metapool/metapool.py
Fix for when the number of items to display is less than five.
=> choices() fix

notebooks/amplicon_pre_prep_file_generator.ipynb
Removes 'plate_number' column from final output.
=> Remove plate_number column from final output

notebooks/amplicon_pre_prep_file_generator.ipynb
redundant filepaths in plate input cell removed.
text notifications for user from MacKenzie added.
=> cleanup, text notifications added

notebooks/amplicon_pre_prep_file_generator.ipynb
Added check to ensure project_names match in the input plate-map file and the user-declared metadata.
=> Fixes #125

metapool/sample_sheet.py
Minor change to capitalize some column names when creating demuxed sample-sheets. This supports easy validation.
=> Minor change to capitalize some column names.

metapool/metapool.py, notebooks/tellseq_syndna.ipynb
This correctly shows only two files different between this dev version and the master.
=> redo of tellseq_syndna changes on updated background

.github/workflows/main.yml, metapool/data/abs_quant_sample_info_calc.yml
Reapply MacKenzie's recent changes as a PR to master branch.
=> Update attribute names, convert tabs to spaces.

metapool/sample_sheet.py, metapool/tests/data/bad-project-name-sample-sheet.csv, metapool/tests/data/scrubbable-sample-sheet.csv, metapool/tests/test_sample_sheet.py
Fixes #172
Added column to Metatranscriptomics sample-sheets. Added additional error-checking to prevent some consistency errors when manually populating empty MetatranscriptomicSampleSheet() objects.
=> Fixes #172

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
Fixes #173 
make_sample_sheet() will now validate a newly-created sample-sheet before returning it to the user. If it fails validation, an Error will be raised in addition to ErrorMessages and WarningMessages being echoed to stdout. This will service the non-notebook API users.
=> Fixes #173

metapool/sample_sheet.py
=> bugfix for declaring new metatranscriptomic class

metapool/sample_sheet.py
=> Add lane-extraction from a sample-sheet

metapool/prep.py, metapool/sample_sheet.py, metapool/scripts/seqpro.py, metapool/scripts/tests/test_seqpro.py, metapool/tests/data/runs/200318_A00953_0082_AH5TWYDSXY/mgv90_test_sheet.csv
The latest changes accumulated after production testing.
=> incorporates the latest changes from production testing.

metapool/count.py, metapool/scripts/tests/test_seqpro.py, metapool/tests/test_count.py, metapool/tests/test_plate.py
Removed these columns as they have been non-functional for quite some time and nobody has requested a need for them.
=> Removed non_host_removal & fraction_non_human from output

setup.py
Amanda has noted that unpredictable behavior may result from metapool being re-installed into environments w/older versions of seaborn and other modules. All recent changes were developed against the current latest versions of all dependencies. Setup.py changes pins the minimum requirements to the current versions.
=> Pinning dependencies to latest versions

metapool/__init__.py, metapool/config/sequencer_types.yml, metapool/sequencers.py, metapool/tests/test_sequencers.py
and ability to select profile_name by instrument id, for use in qp-klp
=> add profile_name entries for sequencers 

metapool/sample_sheet.py, metapool/tests/data/good_pacbio_absquantv10.csv, metapool/tests/data/good_pacbio_metagv10.csv, metapool/tests/test_sample_sheet.py
These do not have "Reads" or "Settings" sections, do not have "BarcodesAreRc", "ForwardAdapter", or "ReverseAdapter" in the Bioinformatics section, and do not have any of the index-related columns in the Data section.  The "Sample_ID" column remains but in practice this id will be the sample barcode, not a munged sample name as it is for Illumina runs.
=> Pac bio sample sheets

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
instead of standard_metag, since with validation now it can no longer be both/either
=> change sheet type for metatv0 to standard_metat
