biocore/kl-metapool

metapool/count.py, metapool/tests/test_count.py
The names of the columns are more generic now, and we've added 2 columns
that show the fraction of reads passing QC and the fraction of reads
passing the human filter.
cc @adswafford
=> ENH: Change column names for count collector

metapool/__init__.py
I believe these elements are needed to make quiet_validate_and_scrub_sample_sheet() importable by other packages.
=> Added references to __init__.py

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
@wasade @antgonza @RodolfoSalido As far as I know, column name remapping for metagenomics and metatranscriptomics should be the same and both have reverse barcodes, right?
=> Adding metatranscriptomics as a valid entry for 'Assay'.

metapool/__init__.py, metapool/scripts/seqpro.py, metapool/scripts/seqpro_mf.py, metapool/scripts/tests/test_seqpro.py, metapool/scripts/tests/test_seqpro_mf.py
Output is one line per file, w/study id in parentheses. (Easily readable by human or machine).
=> Added option to return prep-file output paths w/study id.

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
Previously, make_sample_sheet() would ignore 'Well_description' if it was defined in the input table and instead would generate the column from sample-name values.
This fix will allow 'Well_description' values to reflect as intended when using make_sample_sheet() and accept 'description' and 'well_description' as alternatives in the input table as well.
Code-review confirmed that 'Well_description' is no longer used to obtain the sample-name in metapool.
=> User-defined well_description now working correctly.

.github/workflows/main.yml, metapool/count.py, metapool/tests/test_count.py, setup.py
Simplest fix. Assumes we can always multiply the number of reads by 2. Does not pull raw_reads from fastp JSON files.
raw_reads count extraction previously was accounting only for half of the reads.
=> Fix raw_reads count extraction.

metapool/sample_sheet.py
Give AmpiconSampleSheet a SheetType and SheetVersion, since it's expected that children of KLSampleSheet have them defined. Dummy amplicon sample-sheets are created by SPP to pass to bcl-convert, based on the lab-supplied pre-prep file. Giving it the type 'dummy_amp' avoids having it erroneously say 'standard_metag'.
=> Give AmpliconSampleSheet a SheetType.

metapool/count.py
Removed sanity-check that raises an error if run_counts() finds a fastq.gz file that isn't mentioned in the sample-sheet. This assumption does not hold during plate-level replication where new sample-sheets are created for each replicate. In this case, each new sample-sheet is by definition going to contain only a subset of the sample_ids found in the fastq.gz directory.
=> Removed sanity-check to support plate-level rep

metapool/__init__.py, metapool/sample_sheet.py, metapool/tests/data/test_katharoseq_sheet1.csv, metapool/tests/data/test_katharoseq_sheet2.csv, metapool/tests/data/test_katharoseq_sheet3.csv, metapool/tests/test_sample_sheet.py
metapool can now load and validate metagenomic sample-sheets that optionally contain karathoseq controls along w/extra columns.
A new sample-sheet class for metagenomic sample-sheets has been created and will become the new current version (101). Going forward all metagenomic sample-sheets will have the optional columns functionality.
This will be extended to metatranscriptomic and abs-quant sample-sheets once everything has been reviewed, columns have been agreed upon, etc.
TODO: Add functionality to SampleSheet.add_sample() that can dynamically add columns to the data-section and perform error-handling upon the adding of the first katharoseq sample. This is for manual creation of sample-sheet objects only.
=> Add optional karatho control columns in [Data] section

metapool/sample_sheet.py, metapool/tests/data/replicate_output1.csv, metapool/tests/data/replicate_output2.csv, metapool/tests/data/replicate_output3.csv, metapool/tests/test_sample_sheet.py
Demuxed sample-sheets now use orig_name for their sample-name column values, instead of the sample_name column.
=> Fixed demuxed sample-sheet generation

.github/workflows/main.yml
CI tests that passed three weeks ago failed today, with zero changes to the code.  Tracked this to today's CI run installing a different version of seqtk (1.2) in the metapool environment, while the earlier, passing CI run installed version 1.4.  Pinned to 1.4 or above to prevent this in the future; now the tests pass again ;)
=> Pin seqtk to v1.4 or above to fix spontaneous CI errors

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
Updated load_sample_sheet() to determine the proper SampleSheet() child class to load a file into based on its Assay type, its SheetType, and SheetVersion. If a child class cannot be assigned load_sample_sheet() will continue to raise the generic 'invalid-sample-sheet' message. Otherwise it will return a sheet object and the user will be responsible for running validate_and_scrub() methods and assessing any error messages.
The legacy _parse() method for sample_sheets is perhaps a little cryptic and relies on the csv package. I experimented with implementing a separate parse_header() function using pandas and the read_csv method since the lab is more familiar with it. I believe it works pretty well and it doesn't rely on any legacy functionality in the third party 'sample_sheet' package we …
=> updated load_sample_sheet().

metapool/metapool.py, metapool/mp_strings.py, metapool/tests/test_metapool.py
I discovered this week that, in addition to repeating the code to calculate DNA and water volumes across workflows, the current matrix tube and tellseq notebooks repeat the calculation of "Input DNA" *within* a workflow if you are using synDNA. We are fortunate that that calculation was in fact being done the same way both times, but it is a bug waiting to happen.
This PR creates two new methods in the metapool module that (a) calculate dna and water volumes and add to a plate_df, and (b) calculate Input DNA and add it to a plate_df.  Finally, it *removes* the calculation of Input DNA from `add_syndna`, now requiring that it be done before that call; this will be consistent with the fact that, later, we need the Input DNA column even if we aren't using syndna.
This PR does NOT make use of …
=> centralize functionality repeated in notebooks

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
Fix issue identified for NPH metat sample sheet where sheet was being processed as though it contained replicates when in fact it did not. Issue was traced to `sheet_needs_demuxing` returning "FALSE" instead of `False`, which turned out to be due to `MetatranscriptomicSampleSheetv10` not defining `contains_replicates` as one of its known columns (and therefore not normalizing its values).
To fix, added an explicit definition of the `_KL_ADDTL_DF_SECTIONS`, including the Bioinformatics and Contacts sections, as is done in other sheet types. Also extended the metat v10 sheet load test so that it failed (due to bad `contains_replicates` value)  before this fix and passes after it.
=> fix lack of contains_replicates definition in metat v10 sample sheet

metapool/metapool.py, metapool/tests/test_metapool.py
The wet lab experienced an issue where their input sample accession file had trailing whitespaces in the sample names.  While the existing code will (correctly) throw an error in this case (although I still beefed up the error message a bit), it seems better to just strip the sample accession input prophylactically so they don't have to go back and fix errors manually.
=> strip leading/trailing whitespace from sample accession values

.github/workflows/deploy.yml, deploy.sh, environment.yml
Turns out that to install on the server, I need to be able to pass in prefixes (paths) for BOTH the jupyter kernel AND the conda environment, so rejiggering of the script was necessary.  Changes here:
* I switched over to tag-based (rather than positional) arguments
* code can now handle getting neither prefix, either one, or both
* more command strings are generated in code rather than hardcoded, to support all the different prefix cases
* improved the error handling to be consistent with running these dynamic command strings and with the `set -e` setting
* extended the kernel search to use jupyter if it can (because it will check all places that the jupyter install looks for kernels)
* got rid of conda env activation before running test notebook and instead changed to running it via …
=> Deploy support for jupyter AND conda prefixes

deploy.sh, environment.yml
While prepping for code review, I went over `deploy.sh` very carefully and made a few modifications to polish it up more:
* added a lot more comments and corrected some comment typos
* moved `rollback` function earlier in script (but didn't change)
* removed `report` function and collapsed its functionality into `error_exit` because we don't really need both
* clarified that there are *two* temp dirs in use (and why) and added `trap` statements to ensure they always get cleaned up; removed manual cleanup of these dirs
* removed check that was looking for a pre-existing kernel ONLY if a kernel prefix had been input by the user; now that there is a branch in `kernel_exists` that uses `jupyter` to look for kernels if available, it is worth trying this check even if we aren't looking in a …
=> Deploy tweaks

metapool/metapool.py, metapool/prep.py, metapool/sample_sheet.py, metapool/sequencers.py, metapool/tests/data/test_only_sequencers.yml, metapool/tests/test_prep.py, metapool/tests/test_sequencers.py, notebooks/matrix_tube_pipeline_seqcount_norm.ipynb, sequencer_types.yml
Fix #234 
This pulls data structures and functions out of prep.py and moves them into a config file and a new sequencers.py module (and does the same with test_prep.py and the new test_sequencers.py), and adds a few new methods in sequencers.py to shield code that uses this module from the details of the implementation.  Relatively minimal changes to metapool.py, samplesheet.py, and the matrix tube notebook to use these methods in sequencers.py instead of multiple separate lists.
=> Centralize sequencers

MANIFEST.in, setup.py
I see that `qp-klp` is throwing errors trying to use functions from `sequencers.py` because it can't find the `sequencer_types.yml` file.  I can't be sure, but I suspect this may mean it is not being deployed.
AFAICT, `kl-metapool` has a `manifest.ini` file but that file isn't used since `include_package_data=True` isn't set in `setup.py` (?)  I have therefore added `include_package_data=True` to`setup.py` and added the ``environment.yml`, `deploy.sh`, and `sequencer_types.yml` files to `manifest.ini`.  I commented out `graft notebooks` because it seems to me to potentially conflict with the way notebooks are currently added in the `setup.py` using the `data_files` value.
=> ensure deployment and config files are installed with kl-metapool

metapool/sample_sheet.py, metapool/tests/test_sample_sheet.py
because apparently the existing weird metat v0 is embedded in the qp-klp tests, and the theoretical fix doesn't seem worth the actual effort.
=> put back metatv0-as-metag

metapool/config/sequencer_types.yml, metapool/prep.py, metapool/sequencers.py, metapool/tests/test_prep.py, metapool/tests/test_sequencers.py
* Add platform and sequencing method to `sequencer_types.yml`
* Add code to `preparations_for_run` in `prep.py` to get platform and sequencing method from config rather than use hard-coded
- NOTE: amplicon preps still use hardcoded
* Rename `prep.py`'s `parse_illumina_run_id` to `parse_run_id` and add ability to parse Revio run id
=> Add support for parsing revio run ids and getting prep file platform and sequencing method from sequencer type
